version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    
    volumes:
      - ./backend:/workspace
      - ./backend:/app/backend

    ports:
      - 8000:8000

    command: /bin/sh -c /app/backend/run.sh

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    
    command: sleep infinity

  db:
    container_name: db
    build: 
      context: ./db
      dockerfile: ./Dockerfile

    command: sleep infinity
  