version: '3.7'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    
    volumes:
      - ./backend:/workspace
      - ./backend:/app/backend

    ports:
      - 8000:8000

    command: /bin/sh -c /app/backend/run.sh

    depends_on:
      - db

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    
    volumes:
      - ./frontend:/workspace
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules

    ports:
      - "3000:3000"

    command: /bin/sh -c /app/frontend/run.sh

    depends_on:
      - backend

  db:
    container_name: db
    build: 
      context: ./db
      dockerfile: ./Dockerfile

    restart: unless-stopped
    
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    ports: 
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres



volumes:
  postgres-data:
  node-modules: